title: "danimart1991's Blog"
email: "danimart1991@outlook.com"
description: "One blog more! Another post, another article."
url: "https://www.danielmartingonzalez.com"
twitter_username: "danimart1991"
github_username: "danimart1991"
repository: "danimart1991/danimart1991.github.io"
minimal_mistakes_skin: default
search: true
locale: es
logo: "/assets/images/logo.png"
teaser: "/assets/images/teaser.png"

# Shared Links
twitter:
  username: "danimart1991"
og_image: "/assets/images/logo.png"

# Social Search
social:
  type:  "Person"
  name:  "Daniel Martin Gonzalez"
  links:
    - "https://twitter.com/danimart1991"
    - "https://www.github.com/danimart1991"
    - "https://www.youtube.com/user/danimart1991"
    - "https://instagram.com/danimart1991"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: "Europe/Madrid"

include:
  - _pages

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

google_site_verification: "WAErZAzWb2MenLXs9_lSmuOYrP5izcLA2gG6X8Mjdxo"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-96554215-1"
    anonymize_ip: false

ads:
  google:
    client: ca-pub-4963315397899101

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Martín González"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Mind powered."
  location: "Madrid, Spain"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/danimart1991"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/danimart1991"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danimart1991/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/danimart1991"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/danimart1991"
    - label: "Tip me"
      icon: "fab fa-fw fa-paypal"
      url: "https://www.paypal.me/danimart1991"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/danimart1991"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/danimart1991"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danimart1991/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/danimart1991"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/danimart1991"
    - label: "Tip me"
      icon: "fab fa-fw fa-paypal"
      url: "https://www.paypal.me/danimart1991"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path:
    en: /en/categories/
    es: /es/categorias/
tag_archive:
  type: liquid
  path:
    en: /en/tags/
    es: /es/etiquetas/